package riman

type OrderResponse struct {
	OrderDate               string      `json:"orderDate"`
	MainOrdersPK            int         `json:"mainOrdersPK"`
	OrderType               string      `json:"orderType"`
	FinalOrderType          interface{} `json:"finalOrderType"`
	SiteURL                 string      `json:"siteURL"`
	EncOrderNumber          string      `json:"encOrderNumber"`
	CurrencySymbol          string      `json:"currencySymbol"`
	CurrencyCode            string      `json:"currencyCode"`
	PaidStatus              bool        `json:"paidStatus"`
	HasTaxInvoice           bool        `json:"hasTaxInvoice"`
	HasCommercialInvoice    bool        `json:"hasCommercialInvoice"`
	HasCreditNote           bool        `json:"hasCreditNote"`
	IsShippingPending       bool        `json:"isShippingPending"`
	IsPB                    bool        `json:"isPB"`
	IsPA                    bool        `json:"isPA"`
	IsCC                    bool        `json:"isCC"`
	MainFK                  int         `json:"mainFK"`
	MainOrderTypeFK         int         `json:"mainOrderTypeFK"`
	VoucherURL              interface{} `json:"voucherURL"`
	ShipCountry             string      `json:"shipCountry"`
	ShippingStatus          string      `json:"shippingStatus"`
	OrderShippingStatus     string      `json:"orderShippingStatus"`
	OrderTypeValue          interface{} `json:"orderTypeValue"`
	PaidStatusValue         string      `json:"paidStatusValue"`
	Quantity                int         `json:"quantity"`
	Email                   interface{} `json:"email"`
	Phone                   interface{} `json:"phone"`
	ShipFirstName           interface{} `json:"shipFirstName"`
	ShipLastName            interface{} `json:"shipLastName"`
	MarkedPaidDate          string      `json:"markedPaidDate"`
	Total                   float64     `json:"total"`
	ConvTotal               float64     `json:"convTotal"`
	ConvTotalFormat         string      `json:"convTotalFormat"`
	SubTotal                int         `json:"subTotal"`
	ConvSubtotal            int         `json:"convSubtotal"`
	ShipTotal               float64     `json:"shipTotal"`
	ConvShipTotal           float64     `json:"convShipTotal"`
	Taxes                   float64     `json:"taxes"`
	TaxLabel                string      `json:"taxLabel"`
	ProductTax              float64     `json:"productTax"`
	ShippingTax             int         `json:"shippingTax"`
	AdditionalTaxLabel      string      `json:"additionalTaxLabel"`
	AdditionalTax           interface{} `json:"additionalTax"`
	ConvTaxes               float64     `json:"convTaxes"`
	OrderProcessingFees     interface{} `json:"orderProcessingFees"`
	ConvOrderProcessingFees interface{} `json:"convOrderProcessingFees"`
	Discount                float64     `json:"discount"`
	ConvDiscount            float64     `json:"convDiscount"`
	RefundAmount            int         `json:"refundAmount"`
	ConvRefund              int         `json:"convRefund"`
	SalesCampaignFK         interface{} `json:"salesCampaignFK"`
	Paidstatusfk            int         `json:"paidstatusfk"`
	DeliveryDate            interface{} `json:"deliveryDate"`
	ShippingDetails         interface{} `json:"shippingDetails"`
	OrderItems              interface{} `json:"orderItems"`
	Payments                interface{} `json:"payments"`
	IsPrepaidOrder          interface{} `json:"isPrepaidOrder"`
	ShowInvoice             bool        `json:"showInvoice"`
	ShowOrderInvoice        bool        `json:"showOrderInvoice"`
	KrGuaranteeNo           string      `json:"krGuaranteeNo"`
	WeChatOrderNumber       interface{} `json:"weChatOrderNumber"`
}

type ShippedProductResponse struct {
	PackagePk                 int         `json:"packagePk"`
	ProductPk                 int         `json:"productPk"`
	PackageName               string      `json:"packageName"`
	ProductName               string      `json:"productName"`
	IsPackage                 bool        `json:"isPackage"`
	Quantity                  int         `json:"quantity"`
	Cv                        int         `json:"cv"`
	Sp                        int         `json:"sp"`
	Price                     int         `json:"price"`
	FormattedPrice            string      `json:"formattedPrice"`
	CurrencyCode              string      `json:"currencyCode"`
	ShipmentNumber            string      `json:"shipmentNumber"`
	ShipmentStatus            string      `json:"shipmentStatus"`
	ShippedDate               string      `json:"shippedDate"`
	TrackingNumber            string      `json:"trackingNumber"`
	TrackingLink              string      `json:"trackingLink"`
	VideoOrderPackagingInfoPK interface{} `json:"videoOrderPackagingInfoPK"`
}

type RimanProduct struct {
	ProductPK         int         `json:"productPK"`
	ProductCode       string      `json:"productCode"`
	Sku               interface{} `json:"sku"`
	ProductCategory   string      `json:"productCategory"`
	BrandId           int         `json:"brandId"`
	BrandName         string      `json:"brandName"`
	ProductBrand      interface{} `json:"productBrand"`
	Name              string      `json:"name"`
	ImageUrl          string      `json:"imageUrl"`
	Weight            int         `json:"weight"`
	IsComingSoon      bool        `json:"isComingSoon"`
	ComingSoonMessage interface{} `json:"comingSoonMessage"`
	IsPackage         bool        `json:"isPackage"`
	PackageItems      []struct {
		ProductPK   int    `json:"productPK"`
		Name        string `json:"name"`
		Description string `json:"description"`
		ImgUrl      string `json:"imgUrl"`
		Qty         int    `json:"qty"`
	} `json:"packageItems"`
	IsConfigurable               bool          `json:"isConfigurable"`
	IsProductAvailableOnAutoship bool          `json:"isProductAvailableOnAutoship"`
	IsProductOnAutoship          bool          `json:"isProductOnAutoship"`
	AutoshipProductPk            int           `json:"autoshipProductPk"`
	MaxLimit                     int           `json:"maxLimit"`
	Points                       float64       `json:"points"`
	Bv                           int           `json:"bv"`
	Sp                           int           `json:"sp"`
	ProductMenuId                int           `json:"productMenuId"`
	ProductMenu                  string        `json:"productMenu"`
	Configurations               []interface{} `json:"configurations"`
	Pricing                      []struct {
		PriceType      string `json:"priceType"`
		CurrencySymbol string `json:"currencySymbol"`
		Price          int    `json:"price"`
		NoVatPrice     int    `json:"noVatPrice"`
		FormattedPrice string `json:"formattedPrice"`
		PriceWarning   string `json:"priceWarning"`
	} `json:"pricing"`
	Description string `json:"description"`
	ImageUrls   []struct {
		ImageUrl  string `json:"imageUrl"`
		ImageName string `json:"imageName"`
	} `json:"imageUrls"`
	AdditionalInfo              []interface{} `json:"additionalInfo"`
	Documents                   []interface{} `json:"documents"`
	IsShippable                 bool          `json:"isShippable"`
	IsStarterKit                bool          `json:"isStarterKit"`
	SeqNo                       int           `json:"seqNo"`
	IsFoodProduct               bool          `json:"isFoodProduct"`
	RankInfo                    interface{}   `json:"rankInfo"`
	IsRetailPackage             bool          `json:"isRetailPackage"`
	IsVolumeBasedRSB            bool          `json:"isVolumeBasedRSB"`
	MainType                    int           `json:"mainType"`
	ActiveSmartDelivery         bool          `json:"activeSmartDelivery"`
	IsRedemption                bool          `json:"isRedemption"`
	PriceType                   string        `json:"priceType"`
	DoNotSplitPackBV            bool          `json:"doNotSplitPackBV"`
	SdOnlyPackage               bool          `json:"sdOnlyPackage"`
	ShowSDCheckbox              bool          `json:"showSDCheckbox"`
	OfferAffiliateProgram       bool          `json:"offerAffiliateProgram"`
	OfferPreferredCust          bool          `json:"offerPreferredCust"`
	OfferLoyaltyProgram         bool          `json:"offerLoyaltyProgram"`
	OfferSDOnShop               bool          `json:"offerSDOnShop"`
	IsRetailCart                bool          `json:"isRetailCart"`
	ProductLineId               int           `json:"productLineId"`
	ProductLine                 string        `json:"productLine"`
	ProductFunction             string        `json:"productFunction"`
	MaxLifetimeLimitCatCode     interface{}   `json:"maxLifetimeLimitCatCode"`
	MaxLifetimeLimit            interface{}   `json:"maxLifetimeLimit"`
	JoinMaxLifetimeLimitCatCode string        `json:"joinMaxLifetimeLimitCatCode"`
	JoinMaxLifetimeLimit        int           `json:"joinMaxLifetimeLimit"`
	ProductCmsData              []struct {
		Name    string `json:"name"`
		Value   string `json:"value"`
		DataTag string `json:"dataTag"`
	} `json:"productCmsData"`
}
